# Generated by Django 6.0.3 on 2026-03-17 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='projects_pr_owner_i_242348_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['fork_of'], name='projects_pr_fork_of_8c3467_idx'),
        ),
    ]
