# Generated by Django 6.0.3 on 2026-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_projects_pr_owner_i_242348_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='projects_po_expires_bfecce_idx')],
            },
        ),
    ]
