name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, vmPublic]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          docker compose -p stripboard-editor build
          docker compose -p stripboard-editor up -d
          docker compose -p stripboard-editor restart nginx
